import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nergal' at '24.12.16 0:18' with Gradle 3.1
 *
 * @author nergal, @date 24.12.16 0:18
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
